In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:


# Using sep='|' because the metadata indicates pipe-separated values.
# on_bad_lines='skip' handles the specific row causing the ParserError.
read = pd.read_csv(
    r'D:\ParticipantWiseVolumeData01012022_to_1712025\Identification\125309_1_5_20260723_192035_dat.txt',
    sep='|',
    on_bad_lines='skip'
)

print(f"Successfully loaded {len(read):,} rows.")
read.head()

Successfully loaded 9,849 rows.

   co_code                                       company_name  nse_symbol
0       11                                    20 MICRONS LTD.   20MICRONS
1       14  20TH CENTURY FINANCE CORPORATION PVT. LTD. [ME...  20THCENFIN
2      113                            A A A TECHNOLOGIES LTD.     AAATECH
3      289                                   A B C INDIA LTD.         NaN
4      301                              A B C O PLASTICS LTD.         NaN

In [5]:
reader=pd.read_csv(r'D:\ParticipantWiseVolumeData01012022_to_1712025\options_traded_only(1).csv')
print(reader.shape)

(25125017, 17)

In [6]:
options_df=reader
options_df

,instrument,symbol,expiry_dt,strike_pr,option_typ,open,high,low,close,settle_pr,contracts,val_inlakh,open_int,chg_in_oi,timestamp,bhav_format,trd_date
0,OPTIDX,BANKNIFTY,29-Apr-2010,9200.0,CE,400.00,400.0,400.00,400.00,400.00,1.0,4.800000,6150.0,0.0,01-APR-2010,old,2010-04-01
1,OPTIDX,BANKNIFTY,29-Apr-2010,9400.0,CE,251.00,281.0,234.45,275.45,275.45,24.0,115.820000,17350.0,0.0,01-APR-2010,old,2010-04-01
2,OPTIDX,BANKNIFTY,29-Apr-2010,9500.0,CE,190.05,213.0,185.05,213.00,213.00,20.0,97.019997,16000.0,50.0,01-APR-2010,old,2010-04-01
3,OPTIDX,BANKNIFTY,29-Apr-2010,9600.0,CE,135.05,166.0,130.05,164.30,164.30,226.0,1101.599976,16350.0,9700.0,01-APR-2010,old,2010-04-01
4,OPTIDX,BANKNIFTY,29-Apr-2010,9700.0,CE,90.00,117.0,90.00,116.50,116.50,30.0,146.990005,6100.0,1400.0,01-APR-2010,old,2010-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25125012,OPTSTK,VBL,2025-11-25,490.0,PE,15.00,24.9,15.00,23.90,23.90,639.0,3344.350013,832300.0,-67650.0,2025-10-31,new,2025-10-31
25125013,OPTSTK,VBL,2025-11-25,495.0,PE,17.60,28.8,17.60,27.90,27.90,212.0,1128.844800,208075.0,3075.0,2025-10-31,new,2025-10-31
25125014,OPTSTK,VBL,2025-11-25,500.0,PE,22.90,32.9,22.90,31.80,31.80,302.0,1635.614538,879450.0,-25625.0,2025-10-31,new,2025-10-31
25125015,OPTSTK,VBL,2025-11-25,505.0,PE,28.60,37.1,28.60,36.05,36.05,82.0,452.670750,79950.0,8200.0,2025-10-31,new,2025-10-31
25125016,OPTSTK,VBL,2025-11-25,510.0,PE,35.20,41.5,34.35,40.40,40.40,54.0,303.427675,95325.0,1025.0,2025-10-31,new,2025-10-31

In [7]:

options_df["symbol"].sort_values().unique()

array(['360ONE', '3IINFOTECH', 'AARTIIND', 'ABAN', 'ABB', 'ABBOTINDIA',
       'ABCAPITAL', 'ABFRL', 'ABGSHIP', 'ABIRLANUVO', 'ACC', 'ADANIENSOL',
       'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AIL',
       'AJANTPHARM', 'ALBK', 'ALKEM', 'ALOKTEXT', 'ALSTOMT&D',
       'AMARAJABAT', 'AMBER', 'AMBUJACEM', 'AMTEKAUTO', 'ANDHRABANK',
       'ANGELONE', 'APIL', 'APLAPOLLO', 'APLLTD', 'APOLLOHOSP',
       'APOLLOTYRE', 'AREVAT&D', 'ARVIND', 'ASHOKLEY', 'ASIANPAINT',
       'ASTRAL', 'ATGL', 'ATUL', 'AUBANK', 'AUROPHARMA', 'AXISBANK',
       'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHIND', 'BAJAJHLDNG',
       'BAJFINANCE', 'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK',
       'BANKBARODA', 'BANKINDIA', 'BANKNIFTY', 'BATAINDIA', 'BDL', 'BEL',
       'BEML', 'BERGEPAINT', 'BFUTILITIE', 'BGRENERGY', 'BHARATFIN',
       'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BHUSANSTL', 'BIOCON',
       'BLUESTARCO', 'BOMDYEING', 'BOSCHLTD', 'BPCL', 'BRFL', 'BRITANNIA',
       'BSE', 'BSOFT', 'CADILAHC', 'CAIRN', 'CAMS', 'CANBK', 'CANFINHOME',
       'CAPF', 'CASTROLIND', 'CDSL', 'CEATLTD', 'CENTRALBK', 'CENTURYTEX',
       'CESC', 'CGPOWER', 'CHAMBLFERT', 'CHENNPETRO', 'CHOLAFIN', 'CIPLA',
       'CNXINFRA', 'CNXIT', 'CNXPSE', 'COALINDIA', 'COFORGE', 'COLPAL',
       'CONCOR', 'COREEDUTEC', 'COREPROTEC', 'COROMANDEL', 'CROMPGREAV',
       'CROMPTON', 'CUB', 'CUMMINSIND', 'CYIENT', 'DABUR', 'DALBHARAT',
       'DALMIABHA', 'DCB', 'DCBBANK', 'DCHL', 'DEEPAKNTR', 'DELHIVERY',
       'DELTACORP', 'DENABANK', 'DHANBANK', 'DHFL', 'DISHTV', 'DIVISLAB',
       'DIXON', 'DLF', 'DMART', 'DRREDDY', 'EDUCOMP', 'EICHERMOT', 'EKC',
       'ENGINERSIN', 'EQUITAS', 'ESCORTS', 'ESSAROIL', 'ETERNAL',
       'EXIDEIND', 'FEDERALBNK', 'FINANTECH', 'FINNIFTY', 'FORTIS', 'FRL',
       'FSL', 'FTSE100', 'GAIL', 'GESHIP', 'GITANJALI', 'GLAXO',
       'GLENMARK', 'GMDCLTD', 'GMRAIRPORT', 'GMRINFRA', 'GNFC',
       'GODFRYPHLP', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GRANULES',
       'GRASIM', 'GSFC', 'GSKCONS', 'GSPL', 'GTL', 'GTLINFRA',
       'GTOFFSHORE', 'GUJFLUORO', 'GUJGASLTD', 'GVKPIL', 'HAL', 'HAVELLS',
       'HCC', 'HCLTECH', 'HDFC', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE',
       'HDIL', 'HEROHONDA', 'HEROMOTOCO', 'HEXAWARE', 'HFCL', 'HINDALCO',
       'HINDCOPPER', 'HINDOILEXP', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC',
       'HONAUT', 'HOTELEELA', 'HUDCO', 'IBREALEST', 'IBULHSGFIN',
       'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ICIL', 'ICSA', 'IDBI',
       'IDEA', 'IDFC', 'IDFCBANK', 'IDFCFIRSTB', 'IEX', 'IFCI', 'IGL',
       'IIFL', 'INDHOTEL', 'INDIACEM', 'INDIAINFO', 'INDIAMART',
       'INDIANB', 'INDIGO', 'INDUSINDBK', 'INDUSTOWER', 'INFIBEAM',
       'INFOSYSTCH', 'INFRATEL', 'INFY', 'INOXWIND', 'INTELLECT', 'IOB',
       'IOC', 'IPCALAB', 'IRB', 'IRCTC', 'IREDA', 'IRFC', 'ISPATIND',
       'ITC', 'IVRCLINFRA', 'JETAIRWAYS', 'JINDALSAW', 'JINDALSTEL',
       'JINDALSWHL', 'JIOFIN', 'JISLJALEQS', 'JKCEMENT', 'JPASSOCIAT',
       'JPHYDRO', 'JPPOWER', 'JSL', 'JSWENERGY', 'JSWISPAT', 'JSWSTEEL',
       'JUBLFOOD', 'JUSTDIAL', 'KAJARIACER', 'KALYANKJIL', 'KAYNES',
       'KEI', 'KFA', 'KFINTECH', 'KOTAKBANK', 'KPIT', 'KPITTECH', 'KSCL',
       'KSOILS', 'KTKBANK', 'L&TFH', 'LALPATHLAB', 'LAURUSLABS',
       'LICHSGFIN', 'LICI', 'LITL', 'LODHA', 'LT', 'LTF', 'LTI', 'LTIM',
       'LTM', 'LTTS', 'LUPIN', 'M&M', 'M&MFIN', 'MANAPPURAM', 'MANKIND',
       'MARICO', 'MARUTI', 'MAX', 'MAXHEALTH', 'MAZDOCK', 'MCDOWELL-N',
       'MCLEODRUSS', 'MCX', 'MERCATOR', 'METROPOLIS', 'MFSL', 'MGL',
       'MIDCPNIFTY', 'MINDTREE', 'MINIFTY', 'MLL', 'MOSERBAER',
       'MOTHERSON', 'MOTHERSUMI', 'MPHASIS', 'MRF', 'MRPL', 'MTNL',
       'MUNDRAPORT', 'MUTHOOTFIN', 'NAGARCONST', 'NAGARFERT', 'NAGAROIL',
       'NAM-INDIA', 'NATIONALUM', 'NAUKRI', 'NAVINFLUOR', 'NBCC', 'NCC',
       'NESTLEIND', 'NEYVELILIG', 'NFTYMCAP50', 'NHPC', 'NIFTY',
       'NIFTYCPSE', 'NIFTYIT', 'NIFTYMID50', 'NIFTYNXT50', 'NIITTECH',
       'NMDC', 'NOIDATOLL', 'NTPC', 'NUVAMA', 'NYKAA', 'OBEROIRLTY',
       'OFSS', 'OIL', 'ONGC', 'ONMOBILE', 'OPTOCIRCUI', 'ORBITCORP',
       'ORCHIDCHEM', 'ORIENTBANK', 'PAGEIND', 'PANTALOONR', 'PATANJALI',
       'PATELENG', 'PATNI', 'PAYTM', 'PCJEWELLER', 'PEL', 'PERSISTENT',
       'PETRONET', 'PFC', 'PFIZER', 'PGEL', 'PHOENIXLTD', 'PIDILITIND',
       'PIIND', 'PIRHEALTH', 'PNB', 'PNBHOUSING', 'POLARIS', 'POLICYBZR',
       'POLYCAB', 'POONAWALLA', 'POWERGRID', 'POWERINDIA', 'PPLPHARMA',
       'PRAJIND', 'PREMIERENE', 'PRESTIGE', 'PTC', 'PUNJLLOYD', 'PVR',
       'PVRINOX', 'RAIN', 'RAMCOCEM', 'RANBAXY', 'RAYMOND', 'RBLBANK',
       'RCOM', 'RDEL', 'RECLTD', 'RELCAPITAL', 'RELIANCE', 'RELINFRA',
       'RELMEDIA', 'RENUKA', 'REPCOHOME', 'RNAVAL', 'RNRL', 'ROLTA',
       'RPOWER', 'RUCHISOYA', 'RVNL', 'S&P500', 'SAIL', 'SAMMAANCAP',
       'SAMRUDDHI', 'SBICARD', 'SBILIFE', 'SBIN', 'SCI', 'SESAGOA',
       'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SINTEX', 'SJVN', 'SKSMICRO',
       'SKUMARSYNF', 'SOBHA', 'SOLARINDS', 'SONACOMS', 'SOUTHBANK',
       'SREINFRA', 'SRF', 'SRTRANSFIN', 'SSLT', 'STAR', 'STER',
       'STERLINBIO', 'STRTECH', 'SUNPHARMA', 'SUNTV', 'SUPREMEIND',
       'SUZLON', 'SWIGGY', 'SYNDIBANK', 'SYNGENE', 'TATACHEM',
       'TATACOFFEE', 'TATACOMM', 'TATACONSUM', 'TATAELXSI', 'TATAGLOBAL',
       'TATAMOTORS', 'TATAMTRDVR', 'TATAPOWER', 'TATASTEEL', 'TATATEA',
       'TATATECH', 'TCS', 'TECHM', 'TIINDIA', 'TITAGARH', 'TITAN', 'TMPV',
       'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TRIVENI', 'TTKPRESTIG',
       'TTML', 'TULIP', 'TV-18', 'TV18BRDCST', 'TVSMOTOR', 'UBL',
       'UCOBANK', 'UJJIVAN', 'ULTRACEMCO', 'UNIONBANK', 'UNIPHOS',
       'UNITDSPR', 'UNITECH', 'UNOMINDA', 'UPL', 'VBL', 'VEDL', 'VGUARD',
       'VIDEOIND', 'VIJAYABANK', 'VIPIND', 'VOLTAS', 'WAAREEENER',
       'WELCORP', 'WELGUJ', 'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA', 'YESBANK',
       'ZEEL', 'ZOMATO', 'ZYDUSLIFE'], dtype=object)

In [8]:
# Index symbols
index_symbols = (
    options_df.loc[options_df["instrument"] == "OPTIDX", "symbol"]
    .str.strip()
    .str.upper()
    .unique()
)

# Stock symbols
stock_symbols = (
    options_df.loc[options_df["instrument"] == "OPTSTK", "symbol"]
    .str.strip()
    .str.upper()
    .unique()
)

print("Index symbols :", len(index_symbols))
print("Stock symbols :", len(stock_symbols))

Index symbols : 15
Stock symbols : 459

In [9]:
options_df["symbol"].nunique()

474

In [10]:
symboldata=pd.read_excel(r'D:\ParticipantWiseVolumeData01012022_to_1712025\symbolchangedata.xlsx')

In [11]:
symboldata

       nsesymbol firstsymbol latestsymbol
0     10157PCP24  10157PCP24   10157PCP27
1     10157PCP27  10157PCP24   10157PCP27
2     1201210518  1201210518      CARYSIL
3        ACRYSIL  1201210518      CARYSIL
4        CARYSIL  1201210518      CARYSIL
...          ...         ...          ...
1913     ETERNAL      ZOMATO      ETERNAL
1914      ZOMATO      ZOMATO      ETERNAL
1915   ZUARIAGRO   ZUARIAGRO     ZUARIIND
1916   ZUARIGLOB   ZUARIAGRO     ZUARIIND
1917    ZUARIIND   ZUARIAGRO     ZUARIIND

[1918 rows x 3 columns]

In [12]:
import pandas as pd

# 1. Prepare unique symbols from options_df as a set
remaining_symbols = set(options_df['symbol'].str.strip().str.upper().unique())
total_initial = len(remaining_symbols)

# Prepare symboldata with standardized columns for matching
symbol_map = symboldata.copy()
for col in ['nsesymbol', 'firstsymbol', 'latestsymbol']:
    symbol_map[col] = symbol_map[col].str.strip().str.upper()

# 2. Sequential Matching Logic
# Step A: Match via nsesymbol
match_nse = remaining_symbols.intersection(set(symbol_map['nsesymbol'].unique()))
remaining_symbols -= match_nse

# Step B: Match remaining via latestsymbol
match_latest = remaining_symbols.intersection(set(symbol_map['latestsymbol'].unique()))
remaining_symbols -= match_latest

# Step C: Match remaining via firstsymbol
match_first = remaining_symbols.intersection(set(symbol_map['firstsymbol'].unique()))
remaining_symbols -= match_first

# 3. Report results
print(f"Total unique symbols in options_df: {total_initial}")
print(f"Matches found via 'nsesymbol': {len(match_nse)}")
print(f"Additional matches found via 'latestsymbol': {len(match_latest)}")
print(f"Additional matches found via 'firstsymbol': {len(match_first)}")

total_matched = len(match_nse) + len(match_latest) + len(match_first)
print(f"\nTotal unique symbols matched: {total_matched}")
print(f"Symbols still missing after all checks: {len(remaining_symbols)}")

# Show a sample of what is still missing
print(f"\nSample of missing symbols: {list(remaining_symbols)[:]}")

Total unique symbols in options_df: 474
Matches found via 'nsesymbol': 152
Additional matches found via 'latestsymbol': 0
Additional matches found via 'firstsymbol': 0

Total unique symbols matched: 152
Symbols still missing after all checks: 322

Sample of missing symbols: ['NIFTYCPSE', 'VIJAYABANK', 'TORNTPHARM', 'DENABANK', 'MARUTI', 'GAIL', 'TATACHEM', 'JPASSOCIAT', 'LICI', 'GVKPIL', 'YESBANK', 'CAIRN', 'NYKAA', 'GRASIM', 'ABB', 'PFIZER', 'TITAN', 'PIIND', 'PNB', 'BAJAJFINSV', 'TATAMTRDVR', 'DCHL', 'SRF', 'BRITANNIA', 'KAYNES', 'MANKIND', 'OPTOCIRCUI', 'UNIONBANK', 'JETAIRWAYS', 'DRREDDY', 'PTC', 'TTKPRESTIG', 'ESCORTS', 'PHOENIXLTD', 'M&MFIN', 'PRESTIGE', 'CNXPSE', 'PAYTM', 'NBCC', 'SAMRUDDHI', 'ABGSHIP', 'ASTRAL', 'LUPIN', 'EKC', 'INDIAMART', 'GMDCLTD', 'POLYCAB', 'ICICIBANK', 'GODFRYPHLP', 'IDBI', 'TCS', 'JISLJALEQS', 'NAGAROIL', 'ITC', 'HDIL', 'OIL', 'IREDA', 'APLLTD', 'HINDPETRO', 'LTTS', 'RAYMOND', 'GNFC', 'DALBHARAT', 'SKUMARSYNF', 'IRB', 'EICHERMOT', 'CIPLA', 'SOBHA', 'VBL', 'MRF', 'HDFCAMC', 'SBIN', 'SIEMENS', 'NAUKRI', 'BHARATFORG', 'MANAPPURAM', 'FSL', 'IRFC', 'ONGC', 'LALPATHLAB', 'PATNI', 'CANFINHOME', 'GTOFFSHORE', 'INTELLECT', 'BRFL', 'SYNGENE', 'AUBANK', 'STER', 'NIFTYMID50', 'KSOILS', 'SBICARD', 'GODREJPROP', 'BEL', 'DISHTV', 'BERGEPAINT', 'COALINDIA', 'DELHIVERY', 'STAR', 'HAVELLS', 'IEX', 'BSE', 'AMTEKAUTO', 'HDFCLIFE', 'VGUARD', 'PCJEWELLER', 'PGEL', 'ACC', 'BALKRISIND', 'PNBHOUSING', 'BATAINDIA', 'ICSA', 'GTLINFRA', 'CASTROLIND', 'BLUESTARCO', 'GSFC', 'CUB', 'JINDALSTEL', 'HDFCBANK', 'JUSTDIAL', 'ONMOBILE', 'BANKBARODA', 'CENTRALBK', 'TORNTPOWER', 'PATELENG', 'RENUKA', 'WOCKPHARMA', 'UBL', 'SWIGGY', 'ENGINERSIN', 'ROLTA', 'MRPL', 'CESC', 'UJJIVAN', 'GODREJIND', 'INDIACEM', 'NIFTYNXT50', 'ASHOKLEY', 'EQUITAS', 'RELIANCE', 'HCLTECH', 'IVRCLINFRA', 'DIXON', 'IDEA', 'INDIGO', 'ADANIPOWER', 'RVNL', 'VOLTAS', 'SHREECEM', 'IRCTC', 'RBLBANK', 'DEEPAKNTR', 'COLPAL', 'ANDHRABANK', 'PUNJLLOYD', 'DLF', 'HINDCOPPER', 'CROMPTON', 'SONACOMS', 'IFCI', 'KPITTECH', 'M&M', 'CONCOR', 'IOB', 'GLENMARK', 'CHAMBLFERT', 'LICHSGFIN', 'TATAELXSI', 'HEXAWARE', 'DIVISLAB', 'BDL', 'POWERINDIA', 'RELCAPITAL', 'PERSISTENT', 'SCI', 'SBILIFE', 'ALKEM', 'SYNDIBANK', 'BEML', 'GODREJCP', 'NIFTY', 'BOMDYEING', 'NAGARFERT', 'WAAREEENER', 'SINTEX', 'ALOKTEXT', '3IINFOTECH', 'EDUCOMP', 'PATANJALI', 'CNXIT', 'SJVN', 'BIOCON', 'ESSAROIL', 'UNITECH', 'MOSERBAER', 'BPCL', 'FINNIFTY', 'NMDC', 'MCX', 'METROPOLIS', 'IDFC', 'AJANTPHARM', 'NFTYMCAP50', 'RANBAXY', 'FTSE100', 'KAJARIACER', 'NAVINFLUOR', 'HINDZINC', 'POWERGRID', 'GUJGASLTD', 'HFCL', 'BALRAMCHIN', 'AUROPHARMA', 'BHEL', 'APOLLOHOSP', 'BAJAJHIND', 'DHANBANK', 'AARTIIND', 'RPOWER', 'SUPREMEIND', 'HAL', 'TULIP', 'ULTRACEMCO', 'MAZDOCK', 'JIOFIN', 'RUCHISOYA', 'DMART', 'PPLPHARMA', 'KSCL', 'GRANULES', 'APLAPOLLO', 'MINIFTY', 'LITL', 'MUTHOOTFIN', 'MTNL', 'RNRL', 'NHPC', 'REPCOHOME', 'LODHA', 'CAMS', 'NTPC', 'POLICYBZR', 'MIDCPNIFTY', 'POLARIS', 'TATAPOWER', 'FORTIS', 'PFC', 'LAURUSLABS', 'UCOBANK', 'ORIENTBANK', 'PIDILITIND', 'APOLLOTYRE', 'JSWENERGY', 'LT', 'INDHOTEL', 'GSPL', 'WHIRLPOOL', 'KEI', 'IOC', 'PAGEIND', 'GITANJALI', 'FEDERALBNK', 'BFUTILITIE', 'ALBK', 'INDIANB', 'ABCAPITAL', 'SUZLON', 'TRIVENI', 'NUVAMA', 'MGL', 'CNXINFRA', 'VIPIND', 'GLAXO', 'ABBOTINDIA', 'AMBER', 'IPCALAB', 'TECHM', 'SOUTHBANK', 'TATATECH', 'HINDOILEXP', 'INOXWIND', 'TIINDIA', 'BGRENERGY', 'MCLEODRUSS', 'BANKINDIA', 'MAXHEALTH', 'KALYANKJIL', 'CDSL', 'NATIONALUM', 'WIPRO', 'CEATLTD', 'IGL', 'JUBLFOOD', 'MINDTREE', 'CANBK', 'DABUR', 'JKCEMENT', 'NIFTYIT', 'ADANIGREEN', 'NESTLEIND', 'PREMIERENE', 'ASIANPAINT', 'SUNPHARMA', 'HUDCO', 'NOIDATOLL', 'KFINTECH', 'TV-18', 'PETRONET', 'BAJAJ-AUTO', 'BANKNIFTY', 'SUNTV', 'GESHIP', 'HDFC', 'KTKBANK', 'ORBITCORP', 'ICICIGI', 'INDUSINDBK', 'RECLTD', 'PRAJIND', 'S&P500', 'BANDHANBNK', 'SAIL', 'ICICIPRULI']

In [13]:
import pandas as pd

# 1. Prepare unique symbols from options_df as a set
remaining_symbols = set(options_df['symbol'].str.strip().str.upper().unique())
total_initial = len(remaining_symbols)

# Prepare symboldata with standardized columns for matching
symbol_map = symboldata.copy()
for col in ['nsesymbol', 'firstsymbol', 'latestsymbol']:
    symbol_map[col] = symbol_map[col].str.strip().str.upper()

# 2. Sequential Matching Logic
# Step A: Match via nsesymbol
match_nse = remaining_symbols.intersection(set(symbol_map['nsesymbol'].unique()))
remaining_symbols -= match_nse

# Step B: Match remaining via latestsymbol
match_latest = remaining_symbols.intersection(set(symbol_map['latestsymbol'].unique()))
remaining_symbols -= match_latest

# Step C: Match remaining via firstsymbol
match_first = remaining_symbols.intersection(set(symbol_map['firstsymbol'].unique()))
remaining_symbols -= match_first

# 3. Report results
print(f"Total unique symbols in options_df: {total_initial}")
print(f"Matches found via 'nsesymbol': {len(match_nse)}")
print(f"Additional matches found via 'latestsymbol': {len(match_latest)}")
print(f"Additional matches found via 'firstsymbol': {len(match_first)}")

total_matched = len(match_nse) + len(match_latest) + len(match_first)
print(f"\nTotal unique symbols matched: {total_matched}")
print(f"Symbols still missing after all checks: {len(remaining_symbols)}")

# Show a sample of what is still missing
print(f"\nSample of missing symbols: {list(remaining_symbols)[:]}")

Total unique symbols in options_df: 474
Matches found via 'nsesymbol': 152
Additional matches found via 'latestsymbol': 0
Additional matches found via 'firstsymbol': 0

Total unique symbols matched: 152
Symbols still missing after all checks: 322

Sample of missing symbols: ['NIFTYCPSE', 'VIJAYABANK', 'TORNTPHARM', 'DENABANK', 'MARUTI', 'GAIL', 'TATACHEM', 'JPASSOCIAT', 'LICI', 'GVKPIL', 'YESBANK', 'CAIRN', 'NYKAA', 'GRASIM', 'ABB', 'PFIZER', 'TITAN', 'PIIND', 'PNB', 'BAJAJFINSV', 'TATAMTRDVR', 'DCHL', 'SRF', 'BRITANNIA', 'KAYNES', 'MANKIND', 'OPTOCIRCUI', 'UNIONBANK', 'JETAIRWAYS', 'DRREDDY', 'PTC', 'TTKPRESTIG', 'ESCORTS', 'PHOENIXLTD', 'M&MFIN', 'PRESTIGE', 'CNXPSE', 'PAYTM', 'NBCC', 'SAMRUDDHI', 'ABGSHIP', 'ASTRAL', 'LUPIN', 'EKC', 'INDIAMART', 'GMDCLTD', 'POLYCAB', 'ICICIBANK', 'GODFRYPHLP', 'IDBI', 'TCS', 'JISLJALEQS', 'NAGAROIL', 'ITC', 'HDIL', 'OIL', 'IREDA', 'APLLTD', 'HINDPETRO', 'LTTS', 'RAYMOND', 'GNFC', 'DALBHARAT', 'SKUMARSYNF', 'IRB', 'EICHERMOT', 'CIPLA', 'SOBHA', 'VBL', 'MRF', 'HDFCAMC', 'SBIN', 'SIEMENS', 'NAUKRI', 'BHARATFORG', 'MANAPPURAM', 'FSL', 'IRFC', 'ONGC', 'LALPATHLAB', 'PATNI', 'CANFINHOME', 'GTOFFSHORE', 'INTELLECT', 'BRFL', 'SYNGENE', 'AUBANK', 'STER', 'NIFTYMID50', 'KSOILS', 'SBICARD', 'GODREJPROP', 'BEL', 'DISHTV', 'BERGEPAINT', 'COALINDIA', 'DELHIVERY', 'STAR', 'HAVELLS', 'IEX', 'BSE', 'AMTEKAUTO', 'HDFCLIFE', 'VGUARD', 'PCJEWELLER', 'PGEL', 'ACC', 'BALKRISIND', 'PNBHOUSING', 'BATAINDIA', 'ICSA', 'GTLINFRA', 'CASTROLIND', 'BLUESTARCO', 'GSFC', 'CUB', 'JINDALSTEL', 'HDFCBANK', 'JUSTDIAL', 'ONMOBILE', 'BANKBARODA', 'CENTRALBK', 'TORNTPOWER', 'PATELENG', 'RENUKA', 'WOCKPHARMA', 'UBL', 'SWIGGY', 'ENGINERSIN', 'ROLTA', 'MRPL', 'CESC', 'UJJIVAN', 'GODREJIND', 'INDIACEM', 'NIFTYNXT50', 'ASHOKLEY', 'EQUITAS', 'RELIANCE', 'HCLTECH', 'IVRCLINFRA', 'DIXON', 'IDEA', 'INDIGO', 'ADANIPOWER', 'RVNL', 'VOLTAS', 'SHREECEM', 'IRCTC', 'RBLBANK', 'DEEPAKNTR', 'COLPAL', 'ANDHRABANK', 'PUNJLLOYD', 'DLF', 'HINDCOPPER', 'CROMPTON', 'SONACOMS', 'IFCI', 'KPITTECH', 'M&M', 'CONCOR', 'IOB', 'GLENMARK', 'CHAMBLFERT', 'LICHSGFIN', 'TATAELXSI', 'HEXAWARE', 'DIVISLAB', 'BDL', 'POWERINDIA', 'RELCAPITAL', 'PERSISTENT', 'SCI', 'SBILIFE', 'ALKEM', 'SYNDIBANK', 'BEML', 'GODREJCP', 'NIFTY', 'BOMDYEING', 'NAGARFERT', 'WAAREEENER', 'SINTEX', 'ALOKTEXT', '3IINFOTECH', 'EDUCOMP', 'PATANJALI', 'CNXIT', 'SJVN', 'BIOCON', 'ESSAROIL', 'UNITECH', 'MOSERBAER', 'BPCL', 'FINNIFTY', 'NMDC', 'MCX', 'METROPOLIS', 'IDFC', 'AJANTPHARM', 'NFTYMCAP50', 'RANBAXY', 'FTSE100', 'KAJARIACER', 'NAVINFLUOR', 'HINDZINC', 'POWERGRID', 'GUJGASLTD', 'HFCL', 'BALRAMCHIN', 'AUROPHARMA', 'BHEL', 'APOLLOHOSP', 'BAJAJHIND', 'DHANBANK', 'AARTIIND', 'RPOWER', 'SUPREMEIND', 'HAL', 'TULIP', 'ULTRACEMCO', 'MAZDOCK', 'JIOFIN', 'RUCHISOYA', 'DMART', 'PPLPHARMA', 'KSCL', 'GRANULES', 'APLAPOLLO', 'MINIFTY', 'LITL', 'MUTHOOTFIN', 'MTNL', 'RNRL', 'NHPC', 'REPCOHOME', 'LODHA', 'CAMS', 'NTPC', 'POLICYBZR', 'MIDCPNIFTY', 'POLARIS', 'TATAPOWER', 'FORTIS', 'PFC', 'LAURUSLABS', 'UCOBANK', 'ORIENTBANK', 'PIDILITIND', 'APOLLOTYRE', 'JSWENERGY', 'LT', 'INDHOTEL', 'GSPL', 'WHIRLPOOL', 'KEI', 'IOC', 'PAGEIND', 'GITANJALI', 'FEDERALBNK', 'BFUTILITIE', 'ALBK', 'INDIANB', 'ABCAPITAL', 'SUZLON', 'TRIVENI', 'NUVAMA', 'MGL', 'CNXINFRA', 'VIPIND', 'GLAXO', 'ABBOTINDIA', 'AMBER', 'IPCALAB', 'TECHM', 'SOUTHBANK', 'TATATECH', 'HINDOILEXP', 'INOXWIND', 'TIINDIA', 'BGRENERGY', 'MCLEODRUSS', 'BANKINDIA', 'MAXHEALTH', 'KALYANKJIL', 'CDSL', 'NATIONALUM', 'WIPRO', 'CEATLTD', 'IGL', 'JUBLFOOD', 'MINDTREE', 'CANBK', 'DABUR', 'JKCEMENT', 'NIFTYIT', 'ADANIGREEN', 'NESTLEIND', 'PREMIERENE', 'ASIANPAINT', 'SUNPHARMA', 'HUDCO', 'NOIDATOLL', 'KFINTECH', 'TV-18', 'PETRONET', 'BAJAJ-AUTO', 'BANKNIFTY', 'SUNTV', 'GESHIP', 'HDFC', 'KTKBANK', 'ORBITCORP', 'ICICIGI', 'INDUSINDBK', 'RECLTD', 'PRAJIND', 'S&P500', 'BANDHANBNK', 'SAIL', 'ICICIPRULI']

In [14]:
import pandas as pd

# 1. Prepare unique symbols from options_df as a set
unique_symbols = set(options_df['symbol'].astype(str).str.strip().str.upper().unique())
total_initial = len(unique_symbols)

# 2. Prepare the read dataset nse_symbol values
read_symbols = set(
    read['nse_symbol'].astype(str).str.strip().str.upper().unique()
)

# 3. Match the options symbols against the read dataset's nse_symbol column
matched_symbols = unique_symbols.intersection(read_symbols)
missing_symbols = sorted(unique_symbols.difference(matched_symbols))

# 4. Report results for read dataset
print(f"Total unique symbols in options_df: {total_initial}")
print(f"Matches found in read['nse_symbol']: {len(matched_symbols)}")
print(f"Symbols not found in read['nse_symbol']: {len(missing_symbols)}")

# 5. Display sample matched and missing symbols
print("\nSample matched symbols:")
print(sorted(list(matched_symbols))[:50])

print("\nSample missing symbols:")
print(missing_symbols[:50])

# 6. Now check the unresolved missing symbols against three symboldata columns
symbol_map = symboldata.copy()
for col in ['nsesymbol', 'firstsymbol', 'latestsymbol']:
    symbol_map[col] = symbol_map[col].astype(str).str.strip().str.upper()

missing_df = pd.DataFrame({'symbol': missing_symbols})
missing_df['match_nse_symbol'] = missing_df['symbol'].isin(symbol_map['nsesymbol'])
missing_df['match_firstsymbol'] = missing_df['symbol'].isin(symbol_map['firstsymbol'])
missing_df['match_latestsymbol'] = missing_df['symbol'].isin(symbol_map['latestsymbol'])

missing_df['any_symboldata_match'] = (
    missing_df[['match_nse_symbol', 'match_firstsymbol', 'match_latestsymbol']].any(axis=1)
)

print("\nMissing symbols matching symboldata columns:")
print(missing_df['any_symboldata_match'].sum())
print("\nBreakdown by column:")
print(missing_df[['match_nse_symbol', 'match_firstsymbol', 'match_latestsymbol']].sum())

missing_df

Total unique symbols in options_df: 474
Matches found in read['nse_symbol']: 397
Symbols not found in read['nse_symbol']: 77

Sample matched symbols:
['360ONE', 'AARTIIND', 'ABAN', 'ABB', 'ABBOTINDIA', 'ABCAPITAL', 'ABFRL', 'ABGSHIP', 'ABIRLANUVO', 'ACC', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AJANTPHARM', 'ALBK', 'ALKEM', 'AMBER', 'AMBUJACEM', 'AMTEKAUTO', 'ANDHRABANK', 'ANGELONE', 'APLAPOLLO', 'APLLTD', 'APOLLOHOSP', 'APOLLOTYRE', 'ARVIND', 'ASHOKLEY', 'ASIANPAINT', 'ASTRAL', 'ATGL', 'ATUL', 'AUBANK', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHIND', 'BAJAJHLDNG', 'BAJFINANCE', 'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BATAINDIA', 'BDL', 'BEL', 'BEML']

Sample missing symbols:
['3IINFOTECH', 'AIL', 'ALOKTEXT', 'ALSTOMT&D', 'AMARAJABAT', 'APIL', 'AREVAT&D', 'BANKNIFTY', 'BHUSANSTL', 'CADILAHC', 'CENTURYTEX', 'CNXINFRA', 'CNXIT', 'CNXPSE', 'COREPROTEC', 'CROMPGREAV', 'DCB', 'DHFL', 'FINANTECH', 'FINNIFTY', 'FRL', 'FTSE100', 'GMRINFRA', 'GUJFLUORO', 'HEROHONDA', 'HEXAWARE', 'HOTELEELA', 'IBREALEST', 'IBULHSGFIN', 'IDFCBANK', 'INDIAINFO', 'INFIBEAM', 'INFOSYSTCH', 'INFRATEL', 'ISPATIND', 'JINDALSWHL', 'JPHYDRO', 'KPIT', 'L&TFH', 'LTI', 'LTIM', 'MAX', 'MCDOWELL-N', 'MIDCPNIFTY', 'MINIFTY', 'MLL', 'MOTHERSUMI', 'MUNDRAPORT', 'NAGARCONST', 'NEYVELILIG']

Missing symbols matching symboldata columns:
57

Breakdown by column:
match_nse_symbol      57
match_firstsymbol     43
match_latestsymbol     2
dtype: int64

,symbol,match_nse_symbol,match_firstsymbol,match_latestsymbol,any_symboldata_match
0,3IINFOTECH,False,False,False,False
1,AIL,True,False,False,True
2,ALOKTEXT,False,False,False,False
3,ALSTOMT&D,True,False,False,True
4,AMARAJABAT,True,True,False,True
...,...,...,...,...,...
72,TATAMTRDVR,False,False,False,False
73,TATATEA,True,True,False,True
74,UNIPHOS,True,True,False,True
75,WELGUJ,True,True,False,True
76,ZOMATO,True,True,False,True

In [15]:
# Filter missing symbols that matched any symboldata column
matched_missing_df = missing_df[missing_df['any_symboldata_match']].copy()

symbol_map = symboldata.copy()
for col in ['nsesymbol', 'firstsymbol', 'latestsymbol']:
    symbol_map[col] = symbol_map[col].astype(str).str.strip().str.upper()

read_nse = set(read['nse_symbol'].astype(str).str.strip().str.upper().unique())

remaining = set(matched_missing_df['symbol'])
matched_order = []

for col in ['nsesymbol', 'firstsymbol', 'latestsymbol']:
    if not remaining:
        break

    candidates = symbol_map[symbol_map[col].isin(remaining)].copy()
    if candidates.empty:
        continue

    candidates['candidate_nse'] = candidates['nsesymbol'].astype(str).str.strip().str.upper()
    candidates = candidates[candidates['candidate_nse'].isin(read_nse)]
    if candidates.empty:
        continue

    for orig_sym, group in candidates.groupby(col):
        if orig_sym in remaining:
            matched_order.append({
                'symbol': orig_sym,
                'matched_on': col,
                'candidate_nse': group['candidate_nse'].iloc[0],
                'candidate_rows': len(group),
            })
            remaining.discard(orig_sym)

matched_order_df = pd.DataFrame(matched_order)

print("Matched missing symbols by symboldata columns:")
print(matched_order_df)
print(f"\nRemaining symbols after sequential matching: {len(remaining)}")
print(sorted(remaining)[:50])

Matched missing symbols by symboldata columns:
        symbol   matched_on candidate_nse  candidate_rows
0   AMARAJABAT  firstsymbol         ARE&M               1
1    BHUSANSTL  firstsymbol    TATASTLBSL               1
2     CADILAHC  firstsymbol     ZYDUSLIFE               1
3   CENTURYTEX  firstsymbol         ABREL               1
4   COREPROTEC  firstsymbol    COREEDUTEC               1
5   CROMPGREAV  firstsymbol       CGPOWER               1
6          DCB  firstsymbol       DCBBANK               1
7    FINANTECH  firstsymbol       63MOONS               1
8     GMRINFRA  firstsymbol    GMRAIRPORT               1
9    GUJFLUORO  firstsymbol    GFLLIMITED               1
10   HEROHONDA  firstsymbol    HEROMOTOCO               1
11   HOTELEELA  firstsymbol        HLVLTD               1
12   IBREALEST  firstsymbol         EMBDL               1
13  IBULHSGFIN  firstsymbol    SAMMAANCAP               1
14    IDFCBANK  firstsymbol    IDFCFIRSTB               1
15   INDIAINFO  firstsymbol          IIFL               1
16    INFIBEAM  firstsymbol      CCAVENUE               1
17  INFOSYSTCH  firstsymbol          INFY               1
18    INFRATEL  firstsymbol    INDUSTOWER               1
19    ISPATIND  firstsymbol      JSWISPAT               1
20  JINDALSWHL  firstsymbol         JSWHL               1
21     JPHYDRO  firstsymbol       JPPOWER               1
22        KPIT  firstsymbol         BSOFT               1
23       L&TFH  firstsymbol           LTF               1
24         LTI  firstsymbol           LTM               1
25         MAX  firstsymbol          MFSL               1
26  MCDOWELL-N  firstsymbol      UNITDSPR               1
27         MLL  firstsymbol      MERCATOR               1
28  MOTHERSUMI  firstsymbol     MOTHERSON               1
29  MUNDRAPORT  firstsymbol    ADANIPORTS               1
30  NAGARCONST  firstsymbol           NCC               1
31  NEYVELILIG  firstsymbol      NLCINDIA               1
32    NIITTECH  firstsymbol       COFORGE               1
33  PANTALOONR  firstsymbol           FEL               1
34         PVR  firstsymbol       PVRINOX               1
35     SESAGOA  firstsymbol          VEDL               1
36    SKSMICRO  firstsymbol     BHARATFIN               1
37  SRTRANSFIN  firstsymbol    SHRIRAMFIN               1
38     TATATEA  firstsymbol    TATACONSUM               1
39     UNIPHOS  firstsymbol           UPL               1
40      WELGUJ  firstsymbol       WELCORP               1
41      ZOMATO  firstsymbol       ETERNAL               1

Remaining symbols after sequential matching: 15
['AIL', 'ALSTOMT&D', 'APIL', 'AREVAT&D', 'DHFL', 'FRL', 'LTIM', 'ORCHIDCHEM', 'PIRHEALTH', 'RDEL', 'RNAVAL', 'SSLT', 'STRTECH', 'TATAGLOBAL', 'TATAMOTORS']

In [16]:
# Build the final two-column mapping dataset for direct and mediated matches
read_lookup = read.assign(
    nse_symbol=read['nse_symbol'].astype(str).str.strip().str.upper()
)[['nse_symbol', 'co_code']].drop_duplicates()

# Direct mappings from options_df symbols to read co_code
direct_matches = pd.DataFrame({'symbol': sorted(matched_symbols)})
direct_matches = direct_matches.merge(
    read_lookup,
    left_on='symbol',
    right_on='nse_symbol',
    how='left'
).drop(columns='nse_symbol')

# Mediated mappings via symbol_data -> candidate_nse -> read co_code
mediated_matches = matched_order_df.merge(
    read_lookup,
    left_on='candidate_nse',
    right_on='nse_symbol',
    how='left'
).rename(columns={'symbol': 'options_symbol'})
mediated_matches = mediated_matches[['options_symbol', 'co_code']].rename(columns={'options_symbol': 'symbol'})

# Final map, keeping only successful mappings and exact option symbols
options_to_co_code = pd.concat([direct_matches, mediated_matches], ignore_index=True)
options_to_co_code = options_to_co_code.dropna(subset=['co_code']).drop_duplicates().reset_index(drop=True)

print(f"Direct matches: {direct_matches['symbol'].nunique()}")
print(f"Mediated matches: {mediated_matches['symbol'].nunique()}")
print(f"Total mapped rows: {len(options_to_co_code)}")

options_to_co_code.head(50)

Direct matches: 397
Mediated matches: 42
Total mapped rows: 439

        symbol  co_code
0       360ONE   384392
1     AARTIIND     3998
2         ABAN     4253
3          ABB    21420
4   ABBOTINDIA   121704
5    ABCAPITAL   385189
6        ABFRL   374960
7      ABGSHIP      365
8   ABIRLANUVO    98964
9          ACC    23354
10  ADANIENSOL   502255
11    ADANIENT     5747
12  ADANIGREEN   527121
13  ADANIPORTS    86597
14  ADANIPOWER     5757
15  AJANTPHARM     8893
16        ALBK    11019
17       ALKEM    10884
18       AMBER    12881
19   AMBUJACEM    86607
20   AMTEKAUTO    14268
21  ANDHRABANK    15214
22    ANGELONE   130887
23   APLAPOLLO    35548
24      APLLTD   393826
25  APOLLOHOSP    18102
26  APOLLOTYRE    18151
27      ARVIND    21042
28    ASHOKLEY    22104
29  ASIANPAINT    22859
30      ASTRAL    23696
31        ATGL   389247
32        ATUL    24381
33      AUBANK   380713
34  AUROPHARMA    24685
35    AXISBANK   256066
36  BAJAJ-AUTO   374518
37  BAJAJFINSV   374519
38   BAJAJHIND    28932
39  BAJAJHLDNG    28899
40  BAJFINANCE    28897
41  BALKRISIND    29657
42  BALRAMCHIN    29728
43  BANDHANBNK   524457
44  BANKBARODA    30136
45   BANKINDIA    30148
46   BATAINDIA    31130
47         BDL    33721
48         BEL    33727
49        BEML    33723

In [17]:
# Report unmapped symbols from overall options_df
unique_options_symbols = set(
    options_df['symbol'].astype(str).str.strip().str.upper().unique()
)
mapped_symbols = set(
    options_to_co_code['symbol'].astype(str).str.strip().str.upper().unique()
)
missing_from_overall = sorted(unique_options_symbols.difference(mapped_symbols))

print(f"Total unique symbols in options_df: {len(unique_options_symbols)}")
print(f"Unique mapped symbols in options_to_co_code: {len(mapped_symbols)}")
print(f"Missing symbols count: {len(missing_from_overall)}")
print("\nFirst 35 missing symbols:")
print(missing_from_overall[:35])

missing_from_overall

Total unique symbols in options_df: 474
Unique mapped symbols in options_to_co_code: 439
Missing symbols count: 35

First 35 missing symbols:
['3IINFOTECH', 'AIL', 'ALOKTEXT', 'ALSTOMT&D', 'APIL', 'AREVAT&D', 'BANKNIFTY', 'CNXINFRA', 'CNXIT', 'CNXPSE', 'DHFL', 'FINNIFTY', 'FRL', 'FTSE100', 'HEXAWARE', 'LTIM', 'MIDCPNIFTY', 'MINIFTY', 'NFTYMCAP50', 'NIFTY', 'NIFTYCPSE', 'NIFTYIT', 'NIFTYMID50', 'NIFTYNXT50', 'ORCHIDCHEM', 'PIRHEALTH', 'RDEL', 'RNAVAL', 'RUCHISOYA', 'S&P500', 'SSLT', 'STRTECH', 'TATAGLOBAL', 'TATAMOTORS', 'TATAMTRDVR']

['3IINFOTECH',
 'AIL',
 'ALOKTEXT',
 'ALSTOMT&D',
 'APIL',
 'AREVAT&D',
 'BANKNIFTY',
 'CNXINFRA',
 'CNXIT',
 'CNXPSE',
 'DHFL',
 'FINNIFTY',
 'FRL',
 'FTSE100',
 'HEXAWARE',
 'LTIM',
 'MIDCPNIFTY',
 'MINIFTY',
 'NFTYMCAP50',
 'NIFTY',
 'NIFTYCPSE',
 'NIFTYIT',
 'NIFTYMID50',
 'NIFTYNXT50',
 'ORCHIDCHEM',
 'PIRHEALTH',
 'RDEL',
 'RNAVAL',
 'RUCHISOYA',
 'S&P500',
 'SSLT',
 'STRTECH',
 'TATAGLOBAL',
 'TATAMOTORS',
 'TATAMTRDVR']

In [18]:
# Drop all rows whose symbol did not make it into the final mapped dataset
mapped_symbols = set(
    options_to_co_code['symbol'].astype(str).str.strip().str.upper().unique()
)

# Add co_code to options_df from the final symbol-to-co_code mapping
map_df = options_to_co_code[['symbol', 'co_code']].drop_duplicates().copy()
map_df['symbol'] = map_df['symbol'].astype(str).str.strip().str.upper()

options_df = options_df.copy()
options_df['symbol'] = options_df['symbol'].astype(str).str.strip().str.upper()

options_df = options_df.merge(
    map_df,
    on='symbol',
    how='left'
)

# Keep only rows whose symbol made it into the final mapped dataset
options_df = options_df[
    options_df['symbol'].isin(mapped_symbols)
].copy()

print(f"Rows remaining in options_df after cleanup: {len(options_df)}")
print(f"Unique symbols remaining: {options_df['symbol'].astype(str).str.strip().str.upper().nunique()}")
options_df.head()

Rows remaining in options_df after cleanup: 21521224
Unique symbols remaining: 439

,instrument,symbol,expiry_dt,strike_pr,option_typ,open,high,low,close,settle_pr,contracts,val_inlakh,open_int,chg_in_oi,timestamp,bhav_format,trd_date,co_code
145,OPTSTK,ABAN,29-Apr-2010,1150.0,CA,74.30,78.25,74.30,78.25,78.25,2.0,9.810000,800.0,400.0,01-APR-2010,old,2010-04-01,4253.0
146,OPTSTK,ABAN,29-Apr-2010,1200.0,CA,26.00,51.00,26.00,49.50,49.50,32.0,158.869995,14400.0,1200.0,01-APR-2010,old,2010-04-01,4253.0
147,OPTSTK,ABAN,29-Apr-2010,1250.0,CA,15.15,31.00,15.15,29.00,29.00,38.0,193.740005,14400.0,5200.0,01-APR-2010,old,2010-04-01,4253.0
148,OPTSTK,ABAN,29-Apr-2010,1300.0,CA,11.00,14.75,11.00,14.75,14.75,2.0,10.500000,3200.0,800.0,01-APR-2010,old,2010-04-01,4253.0
149,OPTSTK,ABAN,29-Apr-2010,1400.0,CA,5.00,5.00,5.00,5.00,5.00,1.0,5.620000,2000.0,0.0,01-APR-2010,old,2010-04-01,4253.0

In [19]:
options_df

,instrument,symbol,expiry_dt,strike_pr,option_typ,open,high,low,close,settle_pr,contracts,val_inlakh,open_int,chg_in_oi,timestamp,bhav_format,trd_date,co_code
145,OPTSTK,ABAN,29-Apr-2010,1150.0,CA,74.30,78.25,74.30,78.25,78.25,2.0,9.810000,800.0,400.0,01-APR-2010,old,2010-04-01,4253.0
146,OPTSTK,ABAN,29-Apr-2010,1200.0,CA,26.00,51.00,26.00,49.50,49.50,32.0,158.869995,14400.0,1200.0,01-APR-2010,old,2010-04-01,4253.0
147,OPTSTK,ABAN,29-Apr-2010,1250.0,CA,15.15,31.00,15.15,29.00,29.00,38.0,193.740005,14400.0,5200.0,01-APR-2010,old,2010-04-01,4253.0
148,OPTSTK,ABAN,29-Apr-2010,1300.0,CA,11.00,14.75,11.00,14.75,14.75,2.0,10.500000,3200.0,800.0,01-APR-2010,old,2010-04-01,4253.0
149,OPTSTK,ABAN,29-Apr-2010,1400.0,CA,5.00,5.00,5.00,5.00,5.00,1.0,5.620000,2000.0,0.0,01-APR-2010,old,2010-04-01,4253.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25125012,OPTSTK,VBL,2025-11-25,490.0,PE,15.00,24.90,15.00,23.90,23.90,639.0,3344.350013,832300.0,-67650.0,2025-10-31,new,2025-10-31,262869.0
25125013,OPTSTK,VBL,2025-11-25,495.0,PE,17.60,28.80,17.60,27.90,27.90,212.0,1128.844800,208075.0,3075.0,2025-10-31,new,2025-10-31,262869.0
25125014,OPTSTK,VBL,2025-11-25,500.0,PE,22.90,32.90,22.90,31.80,31.80,302.0,1635.614538,879450.0,-25625.0,2025-10-31,new,2025-10-31,262869.0
25125015,OPTSTK,VBL,2025-11-25,505.0,PE,28.60,37.10,28.60,36.05,36.05,82.0,452.670750,79950.0,8200.0,2025-10-31,new,2025-10-31,262869.0
25125016,OPTSTK,VBL,2025-11-25,510.0,PE,35.20,41.50,34.35,40.40,40.40,54.0,303.427675,95325.0,1025.0,2025-10-31,new,2025-10-31,262869.0

In [22]:
spotprices=pd.read_csv(r'D:\ParticipantWiseVolumeData01012022_to_1712025\Stock_Data\125308_1_120_20260723_191002_dat.txt', sep='|', on_bad_lines='skip')

In [24]:
closing_prices = spotprices[['co_code', 'co_stkdate','nse_closing_price']].copy()

In [25]:
closing_prices

          co_code  co_stkdate  nse_closing_price
0              11  06-10-2008              33.65
1              11  07-10-2008              30.10
2              11  08-10-2008              26.50
3              11  10-10-2008              23.20
4              11  13-10-2008              24.65
...           ...         ...                ...
23141744  2187489  19-03-2026             102.00
23141745  2187489  20-03-2026             102.05
23141746  2187489  24-03-2026             101.75
23141747  2187489  25-03-2026             100.00
23141748  2187489  30-03-2026             109.00

[23141749 rows x 3 columns]

In [ ]:
# Build a date-based lookup from closing_prices
closing_prices_lookup = closing_prices[['co_code', 'co_stkdate', 'nse_closing_price']].drop_duplicates().copy()
closing_prices_lookup['co_code'] = closing_prices_lookup['co_code'].astype('int64')
closing_prices_lookup['co_stkdate'] = pd.to_datetime(closing_prices_lookup['co_stkdate'], errors='coerce', dayfirst=True)

# Prepare options_df for joining
options_df = options_df.copy()
options_df['co_code'] = pd.to_numeric(options_df['co_code'], errors='coerce').astype('int64')
options_df['timestamp_dt'] = pd.to_datetime(options_df['timestamp'], errors='coerce', dayfirst=True)

# Merge on co_code + date and add the closing price column
options_df = options_df.merge(
    closing_prices_lookup.rename(columns={'co_stkdate': 'timestamp_dt'})[
        ['co_code', 'timestamp_dt', 'nse_closing_price']
    ],
    on=['co_code', 'timestamp_dt'],
    how='left',
    suffixes=('', '_closing_prices')
)

options_df['nse_closing_price'] = (
    options_df['nse_closing_price_closing_prices']
    .combine_first(options_df['nse_closing_price'])
)

options_df = options_df.drop(columns=['timestamp_dt', 'nse_closing_price_closing_prices'])

# Optional: check the result
options_df[['symbol', 'timestamp', 'co_code', 'nse_closing_price']].head()

C:\Users\Rishikesh Katakam\AppData\Local\Temp\ipykernel_37528\2541196888.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  options_df['timestamp_dt'] = pd.to_datetime(options_df['timestamp'], errors='coerce', dayfirst=True)

  symbol    timestamp  co_code  nse_closing_price
0   ABAN  01-APR-2010     4253            1199.45
1   ABAN  01-APR-2010     4253            1199.45
2   ABAN  01-APR-2010     4253            1199.45
3   ABAN  01-APR-2010     4253            1199.45
4   ABAN  01-APR-2010     4253            1199.45